services:
  backend:
    image: 290993051085.dkr.ecr.us-east-1.amazonaws.com/engineer-on-click-backend:latest
    container_name: eoc_backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env

  frontend:
    image: 290993051085.dkr.ecr.us-east-1.amazonaws.com/engineer-on-click-frontend:latest
    container_name: eoc_frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
